#!/usr/bin/env python3
import subprocess


subprocess.run(['sudo', 'fbi', '-T', '1', '-noverbose', '-nocomments', '-a', '/home/robot/ev3/mp4_000/mp4_000.jpg'])
subprocess.run(['sudo', 'fbi', '-T', '1', '-noverbose', '-nocomments', '-a', '/home/robot/ev3/mp4_000/mp4_001.jpg'])
subprocess.run(['sudo', 'fbi', '-T', '1', '-noverbose', '-nocomments', '-a', '/home/robot/ev3/mp4_000/mp4_002.jpg'])
subprocess.run(['sudo', 'fbi', '-T', '1', '-noverbose', '-nocomments', '-a', '/home/robot/ev3/mp4_000/mp4_003.jpg'])
subprocess.run(['sudo', 'fbi', '-T', '1', '-noverbose', '-nocomments', '-a', '/home/robot/ev3/mp4_000/mp4_004.jpg'])
subprocess.run(['sudo', 'fbi', '-T', '1', '-noverbose', '-nocomments', '-a', '/home/robot/ev3/mp4_000/mp4_005.jpg'])
subprocess.run(['sudo', 'fbi', '-T', '1', '-noverbose', '-nocomments', '-a', '/home/robot/ev3/mp4_000/mp4_006.jpg'])
subprocess.run(['sudo', 'fbi', '-T', '1', '-noverbose', '-nocomments', '-a', '/home/robot/ev3/mp4_000/mp4_007.jpg'])
subprocess.run(['sudo', 'fbi', '-T', '1', '-noverbose', '-nocomments', '-a', '/home/robot/ev3/mp4_000/mp4_008.jpg'])
subprocess.run(['sudo', 'fbi', '-T', '1', '-noverbose', '-nocomments', '-a', '/home/robot/ev3/mp4_000/mp4_009.jpg'])
subprocess.run(['sudo', 'fbi', '-T', '1', '-noverbose', '-nocomments', '-a', '/home/robot/ev3/mp4_000/mp4_010.jpg'])
subprocess.run(['sudo', 'fbi', '-T', '1', '-noverbose', '-nocomments', '-a', '/home/robot/ev3/mp4_000/mp4_011.jpg'])
subprocess.run(['sudo', 'fbi', '-T', '1', '-noverbose', '-nocomments', '-a', '/home/robot/ev3/mp4_000/mp4_012.jpg'])
subprocess.run(['sudo', 'fbi', '-T', '1', '-noverbose', '-nocomments', '-a', '/home/robot/ev3/mp4_000/mp4_013.jpg'])
subprocess.run(['sudo', 'fbi', '-T', '1', '-noverbose', '-nocomments', '-a', '/home/robot/ev3/mp4_000/mp4_014.jpg'])
subprocess.run(['sudo', 'fbi', '-T', '1', '-noverbose', '-nocomments', '-a', '/home/robot/ev3/mp4_000/mp4_015.jpg'])
subprocess.run(['sudo', 'fbi', '-T', '1', '-noverbose', '-nocomments', '-a', '/home/robot/ev3/mp4_000/mp4_016.jpg'])
subprocess.run(['sudo', 'fbi', '-T', '1', '-noverbose', '-nocomments', '-a', '/home/robot/ev3/mp4_000/mp4_017.jpg'])
subprocess.run(['sudo', 'fbi', '-T', '1', '-noverbose', '-nocomments', '-a', '/home/robot/ev3/mp4_000/mp4_018.jpg'])
subprocess.run(['sudo', 'fbi', '-T', '1', '-noverbose', '-nocomments', '-a', '/home/robot/ev3/mp4_000/mp4_019.jpg'])
subprocess.run(['sudo', 'fbi', '-T', '1', '-noverbose', '-nocomments', '-a', '/home/robot/ev3/mp4_000/mp4_020.jpg'])
subprocess.run(['sudo', 'fbi', '-T', '1', '-noverbose', '-nocomments', '-a', '/home/robot/ev3/mp4_000/mp4_021.jpg'])
subprocess.run(['sudo', 'fbi', '-T', '1', '-noverbose', '-nocomments', '-a', '/home/robot/ev3/mp4_000/mp4_022.jpg'])
subprocess.run(['sudo', 'fbi', '-T', '1', '-noverbose', '-nocomments', '-a', '/home/robot/ev3/mp4_000/mp4_023.jpg'])
subprocess.run(['sudo', 'fbi', '-T', '1', '-noverbose', '-nocomments', '-a', '/home/robot/ev3/mp4_000/mp4_024.jpg'])
subprocess.run(['sudo', 'fbi', '-T', '1', '-noverbose', '-nocomments', '-a', '/home/robot/ev3/mp4_000/mp4_025.jpg'])
subprocess.run(['sudo', 'fbi', '-T', '1', '-noverbose', '-nocomments', '-a', '/home/robot/ev3/mp4_000/mp4_026.jpg'])
subprocess.run(['sudo', 'fbi', '-T', '1', '-noverbose', '-nocomments', '-a', '/home/robot/ev3/mp4_000/mp4_027.jpg'])
subprocess.run(['sudo', 'fbi', '-T', '1', '-noverbose', '-nocomments', '-a', '/home/robot/ev3/mp4_000/mp4_028.jpg'])
subprocess.run(['sudo', 'fbi', '-T', '1', '-noverbose', '-nocomments', '-a', '/home/robot/ev3/mp4_000/mp4_029.jpg'])
subprocess.run(['sudo', 'fbi', '-T', '1', '-noverbose', '-nocomments', '-a', '/home/robot/ev3/mp4_000/mp4_030.jpg'])
subprocess.run(['sudo', 'fbi', '-T', '1', '-noverbose', '-nocomments', '-a', '/home/robot/ev3/mp4_000/mp4_031.jpg'])
subprocess.run(['sudo', 'fbi', '-T', '1', '-noverbose', '-nocomments', '-a', '/home/robot/ev3/mp4_000/mp4_032.jpg'])
subprocess.run(['sudo', 'fbi', '-T', '1', '-noverbose', '-nocomments', '-a', '/home/robot/ev3/mp4_000/mp4_033.jpg'])
subprocess.run(['sudo', 'fbi', '-T', '1', '-noverbose', '-nocomments', '-a', '/home/robot/ev3/mp4_000/mp4_034.jpg'])
subprocess.run(['sudo', 'fbi', '-T', '1', '-noverbose', '-nocomments', '-a', '/home/robot/ev3/mp4_000/mp4_035.jpg'])
        #Ctrl+C --> Ctrl+Shift+V into SSH Terminal
        # sudo python3 /home/robot/ev3/ev3/tests/code/BlendS.py